# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09d52de1e3b8d49f0e2939c2646d17dd0f2a3258f1cdc1ea5903d369ffda36142f23d8a6567874696c27ef45cdab0576f997e954c847e123f6bb907e360d888a

test:
  secret_key_base: c8e6ea1ee7c0f01caf8599c64eca40909a833056e6c61809d4eed5eff07a39b48c2fc9ec0ee1236fdd15726c1a7f67dbeaf430b2e62c0ed86374e2a4c0b6f904

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
